public class CPP {

    enum keywords {
        INT_KEY, DOUBLE_KEY, CHAR_KEY, STRING_KEY,
        FOR_KEY, WHILE_KEY, DO_KEY,
        COUT_KEY, CIN_KEY,
        PRINT_KEY,
        ENDL_KEY,
        SWITCH_KEY, IF_KEY, ELSE_KEY
        };

    enum symbols {
        OPEN_BRACKET_SYM, CLOSE_BRACKET_SYM,
        OPEN_PAREN_SYM, CLOSE_PAREN_SYM,
        OPEN_ANGLE_BRACKET, CLOSE_ANGLE_BRACKET,
        OPEN_SLASH_STAR_SYM, CLOSE_SLASH_STAR_SYM,
        DOUBLE_SLASH_SYM,
        STREAM_TO_SYM, STREAM_FROM_SYM,
        SEMICOLON_SYM, COMMA_SYM, DOT_SYM, PERCENT_SYM, POUND_SYM,
        ASSIGNMENT_SYM, COMPARATOR_EQUALS_SYM,
        COMPARATOR_LESS_THAN_SYM, COMPARATOR_LEQ_SYM, COMPARATOR_GREATER_THAN_SYM, COMPARATOR_GEQ_SYM,
        ADD_SYM, ADD_IS_SYM, INCREMENT_SYM, MINUS_SYM, MINUS_IS_SYM, DECREMENT_SYM,
        MULTIPLY_SYM, MULTIPLY_IS_SYM, DIVIDE_SYM, DIVIDE_IS_SYM,
        ESCAPE_NEWLINE_SYM, ESCAPE_INT_SYM, ESCAPE_FLOAT_SYM, ESCAPE_STRING_SYM
    };

}
